version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - llm-service
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production

  llm-service:
    build: ./llm-service
    ports:
      - "8000:8000"
    volumes:
      - ./llm-service:/app
