version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - llm-service
    environment:
      - NODE_ENV=production
      - LLM_SERVICE_URL=http://llm-service:8000  
    networks:
      - app-network

  llm-service:
    build: ./llm-service
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge